# Dependencies
markdown:            kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               KC Sivaramakrishnan
tagline:             'CTO @ Tarides'
description:         'KC Sivaramakrishnan'
url:                 https://kcsrk.info
baseurl:             ""
paginate:            10
paginate_path:       blog/page:num
excerpt_separator:   ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

# About/contact
author:
  name:              KC Sivaramakrishnan
  url:               https://twitter.com/kc_srk
  email:             sk826@cl.cam.ac.uk

# Custom vars
version:             1.0.0

# Plugins
plugins:             [jekyll-paginate]

future:              true
